//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P31School.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public int SubjectID { get; set; }
        public int PupilID { get; set; }
        public int Grade1 { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Pupil Pupil { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
