//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P31School.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P31SchoolEntities : DbContext
    {
        public P31SchoolEntities()
            : base("name=P31SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTable> AccountTable { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Classroom> Classroom { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Pupil> Pupil { get; set; }
        public virtual DbSet<Schedule> Schedule { get; set; }
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<SubjectTeacherView> SubjectTeacherView { get; set; }
    }
}
