//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P31School.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectTeacherView
    {
        public int TeacherID { get; set; }
        public int SubjectID { get; set; }
        public string SubjectName { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string MidName { get; set; }
    }
}
